version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  aws-cli: circleci/aws-cli@3.1.4
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  build-and-push-images:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and push frontend image
          command: |
            cd frontend
            docker build -t $DOCKER_USERNAME/frontend:${CIRCLE_SHA1:0:7} .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/frontend:${CIRCLE_SHA1:0:7}
            docker tag $DOCKER_USERNAME/frontend:${CIRCLE_SHA1:0:7} $DOCKER_USERNAME/frontend:latest
            docker push $DOCKER_USERNAME/frontend:latest
      - run:
          name: Build and push backend image
          command: |
            cd backend
            docker build -t $DOCKER_USERNAME/backend:${CIRCLE_SHA1:0:7} .
            docker push $DOCKER_USERNAME/backend:${CIRCLE_SHA1:0:7}
            docker tag $DOCKER_USERNAME/backend:${CIRCLE_SHA1:0:7} $DOCKER_USERNAME/backend:latest
            docker push $DOCKER_USERNAME/backend:latest

  deploy-to-eks:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: eks-nebulance
          aws-region: eu-central-1
      - kubernetes/install-kubectl
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - run:
          name: Update Helm values with new image tags
          command: |
            cd helm-charts
            sed -i "s|tag: \"v1\"|tag: \"${CIRCLE_SHA1:0:7}\"|g" values.yaml
      - run:
          name: Deploy application with Helm
          command: |
            cd helm-charts
            helm upgrade --install eks-app . \
              --namespace eks-app \
              --create-namespace \
              --set frontend.image.tag=${CIRCLE_SHA1:0:7} \
              --set backend.image.tag=${CIRCLE_SHA1:0:7}
      - run:
          name: Verify deployment
          command: |
            kubectl get pods -n eks-app
            kubectl get services -n eks-app

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push-images:
          context:
            - docker-hub-creds
          filters:
            branches:
              only: main
      - deploy-to-eks:
          requires:
            - build-and-push-images
          context:
            - aws-creds
          filters:
            branches:
              only: main
