apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-alias
spec:
  selector:
    {{- include "eks-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP