{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eks-app.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-app.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eks-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "eks-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.targetPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        env:
        - name: NODE_ENV
          value: {{ .Values.backend.env.NODE_ENV }}
        - name: PORT
          value: {{ .Values.backend.env.PORT | quote }}
        - name: POSTGRES_HOST
          value: {{ .Values.backend.env.POSTGRES_HOST }}
        - name: POSTGRES_PORT
          value: {{ .Values.backend.env.POSTGRES_PORT | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.secrets.database.name }}
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.secrets.database.name }}
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.secrets.database.name }}
              key: database
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.secrets.application.name }}
              key: jwt-secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.secrets.application.name }}
              key: api-key
{{- end }}