apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-app.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "eks-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database